name: Deploy to joc testnet graphnode
run-name: Deploy ${{ github.ref_name }} to joc testnet graphnode by @${{ github.actor }}
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  subgraph:
    name: Subgraph - Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: sh deploy.sh
        env:
          NETWORK_NAME: "joc-testnet"
          START_BLOCK: "0"
          SUBGRAPH_NAME: "gu-corp/eip721"
          GRAPH_NODE_URL: "http://34.146.178.40:8020" # "https://admin.testnet.sandbox1.japanopenchain.org"
          IPFS_URL: "http://34.146.178.40:5001" # "https://ipfs.testnet.sandbox1.japanopenchain.org"
          VERSION: "${{ github.ref_name }}"